version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: app/frontend/Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./app/frontend/src:/main/src
    command: yarn dev --host
