version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: app/backend/Dockerfile.backend

    ports:
      - "8000:8000"
    volumes:
      - app/backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: .
      dockerfile: app/frontend/Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - app/frontend
    command: yarn dev --host
